---
# handlers file for php_handlers
- name: start php-fpm
  service:
    name: php7.0-fpm
    state: started
  become: true

- name: restart php-fpm
  service:
    name: php7.0-fpm
    state: restarted
  become: true
